config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :patients, only: [:show, :index]
  resources :recommends, only: [:index]
  resources :movies, only: [:index] do
    collection do
      get :streaming
      get :streamnico
    end
  end
  resources :youtubes, only: :index, defaults: { format: :json } do
    collection do
      get :today
    end
  end
  resources :niconicos, only: :index, defaults: {format: :json } do
    collection do
      get :today
    end
  end

  get "/movies/show_niconico/:id" => "movies#show_niconico", :as => :niconico
  get "/movies/show_youtube/:id" => "movies#show_youtube", :as => :youtube

  devise_for :admins

  namespace :admins do
    resources :serifs, :except => [:show]
    resources :youtubemovies, :except => [:show, :destroy, :new, :create]
    resources :niconicomovies, :except => [:show, :destroy, :new, :create]
  end

  root :to => "recommends#index"
end

app/models/patient.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: patients
#
#  id               :integer          not null, primary key
#  twitter_id       :integer
#  name             :string(255)
#  nickname         :string(255)
#  description      :text(65535)
#  icon             :string(255)
#  all_tweet        :integer
#  friend           :integer
#  follower         :integer
#  level            :integer
#  asumi_count      :integer
#  tweet_count      :integer
#  asumi_word       :integer
#  prev_level       :integer
#  prev_level_tweet :integer
#  prev_tweet_count :integer
#  prev_asumi_word  :integer
#  since_id         :string(255)
#  clear            :boolean          default(FALSE), not null
#  protect          :boolean          default(FALSE), not null
#  locked           :boolean          default(FALSE), not null
#  disabled         :boolean          default(FALSE), not null
#  created_at       :datetime
#  updated_at       :datetime
#

class Patient < ApplicationRecord
  has_many :asumi_tweets
  has_many :asumi_levels
  has_one :month_ranking

  validates_uniqueness_of :twitter_id

  validates :twitter_id, :presence => true

  scope :available, -> {
    where(disabled: false).where(locked: false).where(protect: false)
  }

  scope :rankings, -> {
    available.where("prev_tweet_count >?", 10).order("level DESC")
  }

  scope :avail_rankings, -> {
    available.where("prev_tweet_count >?", 10).where("level >?", 20).order("level DESC")
  }

  scope :avail_prev_rankings, -> {
    available.where("prev_level_tweet >?", 10).order("prev_level DESC")
  }

  def asumi_calculate
    if tweet_count == 0
      return 0
    end
    m = asumi_count.to_f / tweet_count.to_f
    m = m * 100
  end
end

app/controllers/patients_controller.rb
# frozen_string_literal: true

class PatientsController < ApplicationController
  layout "user"

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.includes(:asumi_tweets).rankings.take(10)
    @month_ranking = MonthRanking.includes(:patient).level_order.limit(20)
    @prev_rank = Patient.avail_prev_rankings
  end

  # GET /patients/1
  # GET /patients/1.json
  def show
    @patient = Patient.
      includes(:asumi_tweets).
      where(id: params[:id]).
      order("asumi_tweets.tweet_time DESC").first

    redirect_to action: :index and return if @patient.protect

    @all_patients = Patient.rankings

    # for js graph
    @today = Date.current
    @datedata = Date.current.weeks_ago(2)..@today
    @level_data = []
    @levels = AsumiLevel.where(patient_id: params[:id]).where(created_at: Date.current.weeks_ago(2).beginning_of_day...Date.current.end_of_day)
    @level_data = Rails.cache.fetch(@levels) do
      @datedata.map do |day|
        level = @levels.detect { |l| l.created_at.to_date == day }

        if level.present? && level.tweet_count != 0 && level.asumi_count.present?
          level.asumi_count * 100 / level.tweet_count
        else
          0
        end
      end
    end
    gon.leveldata = @level_data
    gon.datedata = @datedata.map { |d| d.prev_day.month.to_s + "/" + d.prev_day.day.to_s }
  end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/index.html.erb
<% cache @patients do %>
  <h4>阿澄度ランキング</h4>
  <div class="update_time">
    <%=l @patients.first.updated_at.beginning_of_day if @patients.present? %>更新
  </div>
  <div id="patient_ranking">
    <div class="left_box">
      <div id="ranking">
        <table class="ranking_tbl">
          <% @patients.each_with_index do |p, i| %>
            <tr onclick="location.href='<%= patient_path(p) %>'">
              <% rank = @prev_rank.index(p) || 2147483648 %>
              <% if i < rank && p.level > 0 %>
                <% updown = "rankup.png" %>
              <% elsif i > rank %>
                <% updown = "rankdown.png" %>
              <% else %>
                <% updown =  "normal.png" %>
              <% end %>
              <th><span class='<%= "ranking_#{i+1}" %>'><%= i + 1 %>位</span><%= image_tag(updown, class: "updown") if updown.present? %><br />
                <span class="gray">(阿澄度<%= p.level %>)</span></th>
              <td class="icon"><%= image_tag(p.icon) %>
                <div class="name"><%= link_to(p.nickname, patient_path(p)) %></div>
              </td>
              <td class="profile">
                <div class="description"><%= p.asumi_tweets.sample(1).first.tweet if p.asumi_tweets.present? %>
                  <div class="hover_profile none"><%= p.description %></div>
                  <div class="screen_name">@<%= p.name %></div>
                </div>
              </td>
            </tr>
          <% end %>
        </table>
      </div>
    </div>
    <div class="right_box">
      <div class="month_ranking">
        <h5 class="dark_blue"><%= Date.current.month %>月のランキング</h5>
        <table>
          <% cache @month_ranking do %>
            <% @month_ranking.first(20).each_with_index do |p,i| %>
              <tr>
                <th><span class='<%= "ranking_#{i+1}" %>'><%= i+1%>位</span><span class="gray">（阿澄度<%= p.level %>）</span></th>
                <td><%= link_to("@" + p.patient.name, patient_path(p.patient)) %></td>
              </tr>
            <% end %>
          <% end %>
        </table>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/patients/index_smart_phone.html.erb
<% cache @patients do %>
  <h3>阿澄度ランキング</h3>
  <div class="update_time">
    <%=l @patients.first.updated_at.beginning_of_day if @patients.present? %>更新
  </div>
  <div id="patient_ranking">
    <div id="ranking">
      <table class="ranking_tbl table">
        <% @patients.each_with_index do |p, i| %>
          <tr>
            <% rank = @prev_rank.index(p) || 2147483648 %>
            <% if i < rank && p.level > 0 %>
              <% updown = "rankup.png" %>
            <% elsif i > rank %>
              <% updown = "rankdown.png" %>
            <% else %>
              <% updown =  "normal.png" %>
            <% end %>
            <th class="rank"><span class='<%= "ranking_#{i+1}" %>'><%= i + 1 %>位  </span><%= image_tag(updown, class: "updown") if updown.present? %><br />
              <span class="gray">(阿澄度<%= p.level %>)</span></th>
            <td class="icon">
              <%= link_to image_tag(p.icon), patient_path(p) %>
            </td>
            <td class="profile non-textdecoration">
              <%= link_to patient_path(p) do %>
                <div class="name"><%= p.nickname %></div>
                <div class="description"><%= p.asumi_tweets.sample(1).first.tweet if p.asumi_tweets.present? %>
                  <div class="screen_name">@<%= p.name %></div>
                </div>
              <% end %>
            </td>
          </tr>
        <% end %>
      </table>
    </div>
  </div>
<% end %>

app/views/patients/show.html.erb
<% cache @patient do %>
  <h4><%= link_to @patient.name + "さんの阿澄病レポート", patient_path(@patient) %></h4>

  <div class="update_time">
    <%=l @patient.updated_at.beginning_of_day %>更新
  </div>
  <div id="patient_show">
    <div class="left_box">
      <div id="chart"></div>
      <table class="report center">
        <tbody>
          <tr>
            <th>
              昨日
            </th>
            <td>
              <b>阿澄度</b><br />
              <%= @patient.level %>%
            </td>
            <td>
              <b>ツイート数</b><br />
              <%= @patient.prev_tweet_count %>
            </td>
            <td>
              <b>阿澄ワード</b><br />
              <%= @patient.prev_asumi_word %>語
            </td>
            <td>
              <b>順位</b><br />
              <% ranking = @all_patients.index {|p| p.id == @patient.id } %>
              <% if ranking.present? %>
                <%= ranking + 1 %>位
              <% else %>
                圏外
              <% end %>
            </td>
          </tr>
        </tbody>
      </table>
      <div id="main_tweet">
        <% cache @patient.asumi_tweets do %>
          <caption><h5>阿澄ツイート</h5></caption>
          <table class="table tweet-area">
            <tbody>
              <% @patient.asumi_tweets.first(25).each do | tweet | %>
                <tr>
                  <td class="tweet"><%= tweet.tweet %>
                    <div class="tweet-detail"><%= link_to "詳細", "http://twitter.com/#{@patient.name}/status/#{tweet.tweet_id}", target: :blank %></div>
                  </td>
                  <td class="tweet-time"><%=l tweet.tweet_time %></td>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% end %>
      </div>
    </div>
    <div class="right_box">
      <div class="content_area ranking">
        <h5>ランキング</h5>
        <table class="ranking">
          <% @all_patients.first(10).each_with_index do |p ,i| %>
            <tr>
              <th><%= i + 1 %>位</th>
              <td><%= link_to "@" + p.name, patient_path(p.id) %></td>
          <% end %>
        </table>
      </div>
    </div>
    <div class="clearfix"></div>
  </div>
<% end %>

app/views/patients/show_smart_phone.html.erb
<% cache @patient do %>
  <h4><%= link_to @patient.name + "さんの阿澄病レポート", patient_path(@patient) %></h4>

  <div class="update_time">
    <%=l @patient.updated_at.beginning_of_day %>更新
  </div>
  <div id="patient_show">
    <div id="chart"></div>
    <table class="report center">
      <tbody>
        <tr>
          <th>
            昨日
          </th>
          <td>
            <b>阿澄度</b><br />
            <%= @patient.level %>%
          </td>
          <td>
            <b>ツイート数</b><br />
            <%= @patient.prev_tweet_count %>
          </td>
          <td>
            <b>阿澄ワード</b><br />
            <%= @patient.prev_asumi_word %>語
          </td>
          <td class="last">
            <b>順位</b><br />
            <% if @ranking.present? %>
              <%= @ranking %>位
            <% else %>
              圏外
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <div id="main_tweet">
      <% cache @patient.asumi_tweets do %>
        <caption><h5>阿澄ツイート</h5></caption>
        <table class="table tweet_area">
          <tbody>
            <% @patient.asumi_tweets.first(25).each do | tweet | %>
              <tr>
                <td class="icon">
                  <%= image_tag(@patient.icon) %>
                </td>
                <td class="tweet"><%= tweet.tweet %>
                  <div class="tweet_detail"><%= link_to "詳細", "http://twitter.com/#{@patient.name}/status/#{tweet.tweet_id}", target: :blank %></div>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
<% end %>