config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :patients, only: [:show, :index]
  resources :recommends, only: [:index]
  resources :movies, only: [:index] do
    collection do
      get :streaming
      get :streamnico
    end
  end
  resources :youtubes, only: :index, defaults: { format: :json } do
    collection do
      get :today
    end
  end
  resources :niconicos, only: :index, defaults: {format: :json } do
    collection do
      get :today
    end
  end

  get "/movies/show_niconico/:id" => "movies#show_niconico", :as => :niconico
  get "/movies/show_youtube/:id" => "movies#show_youtube", :as => :youtube

  devise_for :admins

  namespace :admins do
    resources :serifs, :except => [:show]
    resources :youtubemovies, :except => [:show, :destroy, :new, :create]
    resources :niconicomovies, :except => [:show, :destroy, :new, :create]
  end

  root :to => "recommends#index"
end

app/models/serif.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: serifs
#
#  id         :integer          not null, primary key
#  type       :string(255)
#  word       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Serif < ApplicationRecord
  validates_uniqueness_of :word
end

app/controllers/admin/serifs_controller.rb
class Admin::SerifsController < AdminController
  # GET /serifs
  # GET /serifs.json
  def index
    @notice = params[:notice]
    @serifs = PopularSerif.order(:id).all
    @serifs = @serifs + NewSerif.order(:id).all
    @serifs = @serifs + ReplySerif.order(:id).all

  end

  # GET /serifs/1
  # GET /serifs/1.json
  def show
    @serif = Serif.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /serifs/new
  # GET /serifs/new.json
  def new
  end

  # GET /serifs/1/edit
  def edit
    @notice = params[:notice]
    @serif = Serif.find(params[:id])
  end

  # POST /serifs
  # POST /serifs.json
  def create
    @serif = nil
    case params[:serif][:type]
    when "ReplySerif"
      @serif = ReplySerif.new(params[:serif])
    when "PopularSerif"
      @serif = PopularSerif.new(params[:serif])
    when "NewSerif"
      @serif = NewSerif.new(params[:serif])
    end

    respond_to do |format|
      if @serif.save
        format.html { redirect_to action: "edit", id: @serif.id, notice: 'Serif was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /serifs/1
  # PUT /serifs/1.json
  def update
    @serif = nil
    case params[:serif][:type]
      when "ReplySerif"
          @serif = ReplySerif.find(params[:id])
      when "PopularSerif"
          @serif = PopularSerif.find(params[:id])
      when "NewSerif"
          @serif = NewSerif.find(params[:id])
      else
          @serif = nil
    end

    respond_to do |format|
      if @serif.update_attributes(params[:serif])
        format.html { redirect_to :action => "edit", notice: 'Serif was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /serifs/1
  # DELETE /serifs/1.json
  def destroy
    @serif = Serif.find(params[:id])
    @serif.destroy

    respond_to do |format|
      format.html { redirect_to :action => "index", notice: "Serif was successfully deleted." }
    end
  end
end

app/controllers/admins/serifs_controller.rb
class Admins::SerifsController < AdminsController
  before_action :authenticate_admin!
  # GET /serifs
  # GET /serifs.json
  def index
    @notice = params[:notice]
    @serifs = PopularSerif.order(:id).all
    @serifs = @serifs + NewSerif.order(:id).all
    @serifs = @serifs + ReplySerif.order(:id).all

  end

  # GET /serifs/1
  # GET /serifs/1.json
  def show
    @serif = Serif.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
    end
  end

  # GET /serifs/new
  # GET /serifs/new.json
  def new
  end

  # GET /serifs/1/edit
  def edit
    @notice = params[:notice]
    @serif = Serif.find(params[:id])
  end

  # POST /serifs
  # POST /serifs.json
  def create
    @serif = nil
    case params[:serif][:type]
    when "ReplySerif"
      @serif = ReplySerif.new(permitted_params)
    when "PopularSerif"
      @serif = PopularSerif.new(permitted_params)
    when "NewSerif"
      @serif = NewSerif.new(permitted_params)
    end

    respond_to do |format|
      if @serif.save
        format.html { redirect_to action: "edit", id: @serif.id, notice: 'Serif was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  # PUT /serifs/1
  # PUT /serifs/1.json
  def update
    @serif = nil
    case params[:serif][:type]
      when "ReplySerif"
          @serif = ReplySerif.find(params[:id])
      when "PopularSerif"
          @serif = PopularSerif.find(params[:id])
      when "NewSerif"
          @serif = NewSerif.find(params[:id])
      else
          @serif = nil
    end

    respond_to do |format|
      if @serif.update_attributes(permitted_params)
        format.html { redirect_to :action => "edit", notice: 'Serif was successfully updated.' }
      else
        format.html { render action: "edit" }
      end
    end
  end

  # DELETE /serifs/1
  # DELETE /serifs/1.json
  def destroy
    @serif = Serif.find(params[:id])
    @serif.destroy

    respond_to do |format|
      format.html { redirect_to :action => "index", notice: "Serif was successfully deleted." }
    end
  end

  private
  def permitted_params
    params.require(:serif).permit(:word)
  end
end

app/helpers/serifs_helper.rb
module SerifsHelper
end

app/views/admins/serifs/edit.html.erb
<h1>編集</h1>
<% if @notice.present? %>
  <div class="alert alert-success alert_notice">
    <%= @notice %>
  </div>
<% end %>
<%= form_tag(admins_serif_path, :method => :put) do %>
  <% if @serif.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@serif.errors.count, "error") %> prohibited this serif from being saved:</h2>

      <ul>
      <% @serif.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <table class="table">
    <tr>
      <th>ID</th>
      <td><%= @serif.id %><%= text_field_tag :id , @serif.id, :class => "hidden" %></td>
    </tr>
    <tr>
      <th>type</th>
      <td><%= @serif.type %><%= text_field_tag 'serif[type]', @serif.type, :class => "hidden" %></td>
    </tr>
    <tr>
      <th>台詞</th>
      <td><%= text_field_tag 'serif[word]', @serif.word %></td>
    </tr>
  </table>

  <div class="actions">
    <%= submit_tag "登録" , class: "btn btn-info" %>
  </div>
<% end %>
<%= button_to 'Back', admins_serifs_path, method: :get,  class: "btn" %>
<div class="button_area">
  <%= button_to 'Delete', admins_serif_path(@serif), method: :delete, class:"btn btn-danger", confirm: "本当に削除しますか？"  %>

</div>

app/views/admins/serifs/index.html.erb
<h1>台詞一覧</h1>
<% if @notice.present? %>
  <div class="alert alert-success alert_notice">
    <%= @notice %>
  </div>
<% end %>
<div class="button_area">
  <%= button_to '新規追加', new_admins_serif_path, method: :get, class: "btn btn-info" %>
</div>
<table class="table">
  <tr>
    <th>ID</th>
    <th>type</th>
    <th>台詞</th>
    <th></th>
  </tr>

<% @serifs.each_with_index do |serif, i| %>
  <% if i > 25 %>
    <tr class="none">
  <% else %>
    <tr>
  <% end %>
    <td><%= serif[:id] %></td>
    <td><%= serif[:type] %></td>
    <td><%= serif[:word] %></td>
    <td><%= link_to "編集", edit_admins_serif_path(serif) %></td>
  </tr>
<% end %>
</table>
<div class="center">
  <%= button_tag "続きを読む(#{@serifs.length - 25})", class: "btn more", value: (@serifs.length - 25) %>
</div>
<div class="button_area">
  <%= button_to '新規追加', new_admins_serif_path, method: :get, class: "btn btn-info" %>
</div>

app/views/admins/serifs/new.html.erb
<h1>新規追加</h1>

<%= form_tag(admins_serifs_path, :method => :post) do %>
  <table class="table">
    <tr>
      <th>type</th>
      <td><%= select_tag 'serif[type]', options_for_select([["New","NewSerif"],["Reply","ReplySerif"],["Popular","PopularSerif"]]) %></td>
    </tr>
    <tr>
      <th>台詞</th>
      <td><%= text_field_tag 'serif[word]' %></td>
    </tr>
  </table>

  <div class="actions">
    <%= submit_tag "登録",method: :post, class: "btn btn-info" %>
  </div>
<% end %>

<%= button_to 'Back', admins_serifs_path, method: :get, class: "btn" %>