config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  resources :patients, only: [:show, :index]
  resources :recommends, only: [:index]
  resources :movies, only: [:index] do
    collection do
      get :streaming
      get :streamnico
    end
  end
  resources :youtubes, only: :index, defaults: { format: :json } do
    collection do
      get :today
    end
  end
  resources :niconicos, only: :index, defaults: {format: :json } do
    collection do
      get :today
    end
  end

  get "/movies/show_niconico/:id" => "movies#show_niconico", :as => :niconico
  get "/movies/show_youtube/:id" => "movies#show_youtube", :as => :youtube

  devise_for :admins

  namespace :admins do
    resources :serifs, :except => [:show]
    resources :youtubemovies, :except => [:show, :destroy, :new, :create]
    resources :niconicomovies, :except => [:show, :destroy, :new, :create]
  end

  root :to => "recommends#index"
end

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48724286-2', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/_menu_user_smart_phone.erb
<div class="footer-menu non-textdecoration">
  <ul>
    <%= content_tag(:li, class: params[:controller] == "recommends" ? "current-select" : "") do %>
      <%= link_to "トップ", root_path %>
      <div class="arrow-box">
        <span class="icon-chevron-right"></span>
      </div>
    <% end %>
    <%= content_tag(:li, class: params[:controller] == "patients" ? "current-select" : "") do %>
      <%= link_to "患者たち", patients_path %>
      <div class="arrow-box">
        <span class="icon-chevron-right"></span>
      </div>
    <% end %>
    <li>
      <%= link_to "twitter", "https://twitter.com/asumi_syndrome" %>
      <div class="arrow-box">
        <span class="icon-chevron-right"></span>
      </div>
    </li>
  </ul>
</div>

app/views/layouts/_nav_admin.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </a>
      <a class="brand" href="#">Admin</a>
      <div class="container nav-collapse">
	<ul class="nav">
	  <li><%= link_to "Serifs", admins_serifs_path  %></li>
	  <li><%= link_to "Youtube", admins_youtubemovies_path %></li>
	  <li><%= link_to "Niconico", admins_niconicomovies_path %></li>
	</ul>
	<ul class="left">
	  <li><%= link_to "SignOut", destroy_admin_session_path, method: :delete %></li>
	</ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_nav_user.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </a>
      <%= link_to("阿澄ちゃん", root_path, class: "brand") %>
      <div class="container nav-collapse">
	<ul class="nav">
	  <li><%= link_to "おすすめ", root_path %></li>
	  <li><%= link_to "患者たち", patients_path  %></li>
	  <li><%= link_to "作業用あすみん", streaming_movies_path %></li>
	</ul>
	<%= form_tag(movies_path, :method => :get, :class=>"search_form") do |f| %>
	  <div class="search_field">
	    <%= text_field_tag :search, nil,:class=> "search_text",:placeholder => "動画検索" %>
	    <%= submit_tag "検索", class: "btn search_btn" %></div>
	<% end %>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</div>

app/views/layouts/_nav_user_smart_phone.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
        <span class="icon-search"></span>
      </a>
      <%= link_to("阿澄ちゃん", root_path, class: "brand") %>
      <div class="container nav-collapse">
        <%= form_tag(movies_path, :method => :get, :class=>"search_form") do |f| %>
          <div class="search_field">
            <%= text_field_tag :search, nil,:class=> "search_text",:placeholder => "動画検索" %>
            <%= submit_tag "検索", class: "btn search_btn" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_side_admin.html.erb
<div class="span3">
  <div class="well sidebar-nav">
    <h3>Sidebar</h3>
    <ul class="nav nav-list">
      <li class="nav-header">Sidebar</li>
      <li><%= link_to "Link1", "/path1"  %></li>
      <li><%= link_to "Link2", "/path2"  %></li>
      <li><%= link_to "Link3", "/path3"  %></li>
    </ul>
  </div><!--/.well -->
</div><!--/span-->

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "阿澄ちゃん -管理-" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "admin", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%#= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%#= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>
    <%= include_gon %>

  </head>
  <body>

    <%= render "layouts/nav_admin" %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <div class="container">
      <div id="main_area">
        <div class="row">
            <%= bootstrap_flash %>
            <%= yield %>
	  <%#= render "layouts/side_admin" %>
        </div><!--/row-->
	</div>
      <footer>
        <p>&copy; 2013-2015 Akira Fukushima</p>
      </footer>

    </div> <!-- /container -->
    <%= javascript_include_tag "admin" %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "阿澄ちゃん" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="container">
      <div id="main_area">
        <div class="row">
          <%= bootstrap_flash %>
          <%= yield %>
          <%#= render "layouts/side_admin" %>
        </div><!--/row-->
      </div>
      <footer>
        <p>&copy; 2013-2017 <%= link_to "@h3_poteto", "https://twitter.com/h3_poteto" %></p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/user.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + " - 阿澄ちゃん" : "阿澄ちゃん" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "user", :media => "all" %>

    <%= include_gon %>

  </head>
  <body data-controller=<%= params[:controller] %> data-action=<%= params[:action] %>>
    <div class="background"></div>
    <div class="blur"></div>
    <%= render "layouts/nav_user" %>
    <div class="container">
      <div id="main_area">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      <footer>
        <p>&copy; 2013-2017 <%= link_to "@h3_poteto", "https://twitter.com/h3_poteto" %></p>
      </footer>
    </div>
    <%= javascript_include_tag "user" %>
    <% if Settings.analytics %>
      <%= render "layouts/google_analytics" %>
    <% end %>
  </body>
</html>

app/views/layouts/user_smart_phone.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) + " - 阿澄ちゃん" : "阿澄ちゃん" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "user_smart_phone", :media => "all" %>

    <%= include_gon %>

  </head>
  <body data-controller=<%= params[:controller] %> data-action=<%= params[:action] %>>
    <div class="background"></div>
    <div class="blur"></div>
    <%= render "layouts/nav_user" %>
    <div class="container">
      <div id="main_area">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      <%= render "layouts/menu_user_smart_phone" %>
      <footer>
        <p>&copy; 2013-2015 <%= link_to "@h3_poteto", "https://twitter.com/h3_poteto" %></p>
      </footer>
    </div>
    <%= javascript_include_tag "user_smart_phone" %>
    <% if Settings.analytics %>
      <%= render "layouts/google_analytics" %>
    <% end %>
  </body>
</html>